"""Regenerate WALKTHROUGH.md from real runs of dte on a toy project.  dte:B29,C14

Run: python tools/walkthrough.py
"""
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DTE = os.path.join(ROOT, "tools", "dte.py")
work = tempfile.mkdtemp(prefix="dte-walk-")
sections = []


def sh(cmd, note=None, show=True):
    """Run a dte command (list of args after 'dte') and record it."""
    out = subprocess.run([sys.executable, DTE, "--root", work] + cmd, capture_output=True, text=True).stdout
    out = out.replace(work.replace("\\", "/"), ".").replace(work, ".")
    out = out.replace(os.path.relpath(DTE, work).replace(os.sep, "/"), "dte.py")
    block = "```\n$ dte %s\n%s```\n" % (" ".join(q(a) for a in cmd), out if show else "")
    sections.append(((note + "\n\n") if note else "") + block)
    return out


def q(a):
    for w in (work, work.replace("\\", "/")):
        if a.startswith(w):
            a = a[len(w):].lstrip("\\/").replace("\\", "/")
    return '"%s"' % a if " " in a else a


def write(rel, text):
    p = os.path.join(work, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def git(*a):
    subprocess.run(["git", "-C", work] + list(a), capture_output=True)


def h(text):
    sections.append(text + "\n")


git("init", "-q")
git("config", "user.email", "walk@example.com")
git("config", "user.name", "walk")

h("<!-- transcript of a toy project: the dte: tokens below belong to that tree. "
  "Regenerate with tools/walkthrough.py. Governed by B29, C14, B27, B24. -->\n# Walkthrough\n\n"
  "Every block below is real output from `tools/dte.py` on a toy project, generated by "
  "`tools/walkthrough.py`, so it is exact for this version. The project is a small service "
  "with a config loader. Owner is `ada`, the agent is `bot`.")
h("## Day one")
sh(["init"], "Scaffold the project.")
sh(["new", "A", "--title", "Config comes from one source of truth at startup", "--by", "ada", "--made-by", "human",
    "--decision", "All configuration is read once at startup from a single declared source.",
    "--why", "Runtime config drift caused two outages last year."], "The owner writes the core. Ring A has no parents.")
sh(["new", "A", "--title", "The service stays runnable by one person on a laptop", "--by", "ada", "--made-by", "human",
    "--decision", "Everything needed to run locally is in the repo.",
    "--why", "Onboarding time is the constraint, not throughput."])
sh(["new", "B", "--title", "Config is a single YAML file, path given by CONFIG_PATH", "--by", "bot", "--parents", "A1,A2",
    "--decision", "One YAML file. Its path is CONFIG_PATH; default ./config.yml.",
    "--why", "One file satisfies A1; a checked-in default satisfies A2.", "--confidence", "medium"],
   "The agent decides at ring B, citing both core goals.")
sh(["new", "B", "--title", "Config values are validated against a schema before use", "--by", "bot", "--parents", "A1",
    "--decision", "Loaded config is validated; the service refuses to start on a schema error.",
    "--why", "A1 makes the file the only source; a bad file must fail loudly."])
sh(["new", "C", "--title", "The schema lives next to the loader as a Python dict", "--by", "bot", "--parents", "B2",
    "--decision", "schema.py holds a dict; no schema library.",
    "--why", "No dependency for one dict (A2 wants a laptop-runnable repo)."], "Ring C: how B2 is implemented.")
h("Then the code, and citations from it.")
write("src/config.py", "import os, yaml\n\ndef load():\n    path = os.environ.get('CONFIG_PATH', './config.yml')\n"
                       "    return yaml.safe_load(open(path))\n")
write("src/schema.py", "SCHEMA = {'port': int, 'name': str}\n")
write("src/validate.py", "from schema import SCHEMA\n\ndef check(cfg):\n    for k, t in SCHEMA.items():\n"
                         "        assert isinstance(cfg[k], t), k\n")
write("config.yml", "port: 8080\nname: demo\n")
sh(["cite", os.path.join(work, "src", "config.py"), "B1"])
sh(["cite", os.path.join(work, "src", "schema.py"), "C1"])
sh(["cite", os.path.join(work, "src", "validate.py"), "B2"])
sh(["coverage"], "One file is still uncited. Coverage is a report, never a gate.")
sh(["cite", os.path.join(work, "config.yml"), "B1"])
sh(["validate"], "The tree is consistent. The agent's nodes are listed for the owner to ratify.")
git("add", "-A")
git("commit", "-q", "-m", "day one")

h("## Reading the tree")
sh(["tree", "--files"])
sh(["show", "C1"], "One decision, without opening the file.")
sh(["trace", os.path.join(work, "src", "schema.py")], "Why does this file exist?")
sh(["blast", "B2"], "What would changing B2 touch?")

h("## The owner ratifies")
sh(["ratify", "B1", "B2", "--by", "ada"],
   "Ratified nodes become human-held: an agent can no longer retire or move them without a human's name.")

h("## A subagent is briefed")
sh(["brief", "C", "--under", "B2"], "An orchestrator at ring B spawns a subagent to work under B2 and hands it this block.")

h("## Reverting a decision")
sh(["retire", "B2", "--by", "bot"], "The agent tries to revert the human-held B2 and is refused.")
sh(["retire", "B2", "--by", "bot", "--authorized-by", "ada"],
   "With the owner's authorization the revert goes through. The report is the blast radius.")
git("add", "-A")
git("commit", "-q", "-m", "revert B2")
sh(["validate"], "Validation now fails until every item in that radius is dealt with. "
                 "C1 is an orphan; validate.py cites a retired node.")
sh(["reparent", "C1", "--parents", "B1", "--by", "bot"], "The agent re-parents the orphan. Frontmatter is never hand-edited.")
write("src/validate.py", "# dte:B1\nfrom schema import SCHEMA\n\ndef check(cfg):\n    for k, t in SCHEMA.items():\n"
                         "        assert isinstance(cfg[k], t), k\n")
sh(["validate"], "After re-pointing the citation in validate.py, the tree is consistent again. "
                 "B2 lives in the ledger and in git history.")
sh(["retired"])

h("## Promoting a decision")
sh(["scope"], "Advisory checks. Nothing to report on a tree this small.")
sh(["move", "C1", "B", "--by", "bot", "--parents", "A2"],
   "The agent decides the schema location is really a rule, not an implementation detail, and promotes it. "
   "New ID, old one retired, references rewritten.")
sh(["validate"])
sh(["show", "B3"])

h("## Integrating")
sh(["export", "--out", os.path.join(work, "tree.json")],
   "The JSON is the join surface for a structural graph: `citations[].file` is the key.")
h("That is the whole life cycle: write the core, decide beneath it, cite, validate, ratify, brief, revert, "
  "repair, promote, export. Nothing above was typed into a frontmatter block by hand.")

text = "\n".join(sections)
with open(os.path.join(ROOT, "WALKTHROUGH.md"), "w", encoding="utf-8", newline="\n") as fh:
    fh.write(text)
shutil.rmtree(work, ignore_errors=True)
print("wrote WALKTHROUGH.md, %d chars" % len(text))
